# Generated by Django 2.2 on 2021-01-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50, unique=True)),
                ('isi', models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita, animi! Accusantium quis sunt vitae, iste sit voluptate eos saepe adipisci cupiditate ratione harum qui vel at reiciendis maiores? Illum fugiat consequuntur quibusdam architecto ullam, optio qui quas ut nesciunt obcaecati maiores beatae minus error praesentium corporis fuga distinctio, quisquam excepturi.', max_length=1000)),
                ('penulis', models.CharField(max_length=30)),
                ('foto', models.FileField(upload_to='')),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
